module.exports = [
    {
        user: 'Hammed',
        onTrack: 5,
        atRisk: 5,
        behind: 5,
        goals: 5,
        date: '2021-10-22',
      },
    {
      user: 'Femi',
      onTrack: 5,
      atRisk: 13,
      behind: 20,
      goals: 2,
      date: '2021-10-22',
    },
    {
        user: 'Tolu',
        onTrack: 5,
        atRisk: 10,
        behind: 1,
        goals: 2,
        date: '2021-10-23',
    },
    {
        user: 'Femi',
        onTrack: 5,
        atRisk: 3,
        behind: 10,
        goals: 1,
        date: '2021-10-23',
    },
    {
        user: 'Femi',
        onTrack: 3,
        atRisk: 10,
        behind: 2,
        goals: 1,
        date: '2021-10-23',
    },
    {
        user: 'Tolu',
        onTrack: 5,
        atRisk: 3,
        behind: 2,
        goals: 10,
        date: '2021-10-24',
    },
    {
        user: 'Femi',
        onTrack: 4,
        atRisk: 3,
        behind: 9,
        goals: 1,
        date: '2021-10-25',
    },
  ];
